#!/bin/bash

PARAM_COMPILER="g++"
PARAM_OPTIMIZATION="-O0"
PARAM_INTEL="-masm=intel"
PARAM_ASSEMBLER="-S"
PARAM_ASSEMBLER_VERBOSE="-fverbose-asm"

SOURCE="main.cpp"

"$PARAM_COMPILER" $PARAM_OPTIMIZATION $PARAM_INTEL $PARAM_ASSEMBLER "$SOURCE"